### ISSUE TITLE
Import failing

### ISSUE THREAD

**Issue by cbyrohl** [norok2/flyingcircus#1]
Upon import of flyingcircus, I get the following error:

```
Traceback (most recent call last):
  File "create.py", line 5, in <module>
    import raster_geometry
  File "/usr/local/lib/python3.9/dist-packages/raster_geometry/__init__.py", line 21, in <module>
    from flyingcircus import msg, dbg, fmt, fmtm, elapsed, report, pkg_paths
  File "/usr/local/lib/python3.9/dist-packages/flyingcircus/__init__.py", line 727, in <module>
    PATH = pkg_paths(__file__, INFO['name'], INFO['author'], INFO['version'])
  File "/usr/local/lib/python3.9/dist-packages/flyingcircus/__init__.py", line 706, in pkg_paths
    os.makedirs(dirpath)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/root/.config/FlyingCircus/0.1.4.0'
```
I use a fresh docker container and have multiple parallel calls importing flyingcircus. I believe adding exist_ok=True in the makedirs call here
``` python

    for name, dirpath in dirpaths.items():
        if not os.path.isdir(dirpath):
            os.makedirs(dirpath)
```
in \_\_init\_\_.py should fix the issue.

**Comment by norok2** [comment]
Hi,
A single non-concurrent import should avoid this issue, and then subsequent concurrent imports should work. I am not sure `exist_ok` trick would do, because you may have a file with the same name as the directory trying to be created which would make `makedirs` happy, but you would experience later problems once the directory is being used as a directory while it is not. Perhaps, one could refine the statement to throw a warning in case a conflicting file exists. I'll look into it.

**Comment by cbyrohl** [comment]
I think introducing a specific import in test files for this package is more of a workaround than a fix. The solution above seems to work well, see PR. Cheers!
